service: glossary-reminder

frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221

functions:
  glossary-reminder:
    handler: dist/handler.handler
    name: glossary-reminder
    memorySize: 256
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - GlossaryReminderTriggerQueue
              - Arn
    #   # Invoke Lambda function every minute
    #   - schedule: rate(30 minute)

resources:
  Resources:
    GlossaryReminderTriggerQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: glossary-reminder-trigger-queue
