service: glossary-reminder

frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221

functions:
  glossary-reminder:
    handler: dist/handler.handler
    events:
      # Invoke Lambda function every minute
      - schedule: rate(30 minute)
