service: glossary-reminder

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: stella-projects-artifacts
    maxPreviousDeploymentArtifacts: 5

functions:
  glossary-reminder:
    handler: dist/handler.handler
    name: glossary-reminder
    memorySize: 256
    environment:
      - GLOSSARY_RETRIEVER_TOPIC:
          Fn::GetAtt:
            - GlossaryReminderTriggerQueue
            - Arn
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - GlossaryReminderTriggerQueue
              - Arn
    #   # Invoke Lambda function every minute
    #   - schedule: rate(30 minute)

resources:
  Resources:
    GlossaryReminderTriggerQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: glossary-reminder-trigger-queue

    ## SNS Topic
    GlossaryReminderTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: glossary-reminder-topic

    GlossaryReminderTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Id: GlossaryReminderTopicPolicy
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                AWS: "*"
              Action:
                - sns:Publish
                - sns:Subscribe
              Resource: "*"
        Topics:
          - !Ref GlossaryReminderTopic

    ## SNS Subscription
    GlossaryReminderTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn:
          Fn::GetAtt:
            - GlossaryReminderTriggerQueue
            - Arn
        Protocol: email
        Endpoint: stella.hu.xing@gmail.com
