name: Glossary-Reminder

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pipeline:
    name: pipeline.yml
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.ACCESSKEYID }} --secret ${{ secrets.ACCESSSECRET }}

      - name: Format & Build
        run: npm run lint && npm run build

      - name: Deploy
        run: npm run deploy
